services:
  - type: web
    name: stok-satis-takip
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
